/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.lcd.demo.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the Student service. Represents a row in the &quot;student&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.lcd.demo.model.impl.StudentModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.lcd.demo.model.impl.StudentImpl}.
 * </p>
 *
 * @author Smile
 * @see Student
 * @see com.lcd.demo.model.impl.StudentImpl
 * @see com.lcd.demo.model.impl.StudentModelImpl
 * @generated
 */
public interface StudentModel extends BaseModel<Student> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a student model instance should use the {@link Student} interface instead.
	 */

	/**
	 * Returns the primary key of this student.
	 *
	 * @return the primary key of this student
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this student.
	 *
	 * @param primaryKey the primary key of this student
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the student ID of this student.
	 *
	 * @return the student ID of this student
	 */
	public long getStudentId();

	/**
	 * Sets the student ID of this student.
	 *
	 * @param studentId the student ID of this student
	 */
	public void setStudentId(long studentId);

	/**
	 * Returns the name of this student.
	 *
	 * @return the name of this student
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this student.
	 *
	 * @param name the name of this student
	 */
	public void setName(String name);

	/**
	 * Returns the age of this student.
	 *
	 * @return the age of this student
	 */
	public int getAge();

	/**
	 * Sets the age of this student.
	 *
	 * @param age the age of this student
	 */
	public void setAge(int age);

	/**
	 * Returns the gender of this student.
	 *
	 * @return the gender of this student
	 */
	@AutoEscape
	public String getGender();

	/**
	 * Sets the gender of this student.
	 *
	 * @param gender the gender of this student
	 */
	public void setGender(String gender);

	/**
	 * Returns the phone of this student.
	 *
	 * @return the phone of this student
	 */
	public int getPhone();

	/**
	 * Sets the phone of this student.
	 *
	 * @param phone the phone of this student
	 */
	public void setPhone(int phone);

	/**
	 * Returns the address of this student.
	 *
	 * @return the address of this student
	 */
	@AutoEscape
	public String getAddress();

	/**
	 * Sets the address of this student.
	 *
	 * @param address the address of this student
	 */
	public void setAddress(String address);

	/**
	 * Returns the file image of this student.
	 *
	 * @return the file image of this student
	 */
	public long getFileImage();

	/**
	 * Sets the file image of this student.
	 *
	 * @param fileImage the file image of this student
	 */
	public void setFileImage(long fileImage);

	/**
	 * Returns the link image of this student.
	 *
	 * @return the link image of this student
	 */
	@AutoEscape
	public String getLinkImage();

	/**
	 * Sets the link image of this student.
	 *
	 * @param linkImage the link image of this student
	 */
	public void setLinkImage(String linkImage);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(Student student);

	public int hashCode();

	public CacheModel<Student> toCacheModel();

	public Student toEscapedModel();

	public String toString();

	public String toXmlString();
}